### ISSUE TITLE
Question about making masks

### ISSUE THREAD

**Issue by jmliu88** [preddy5/multi_implicit_fonts#3]
Hi, 

This work is really inspiring! I'm trying to make the mask_np files with my own font data. Would you release the script about it? Or a small description would also be helpful.

Thanks,
James

**Comment by preddy5** [comment]
Hey @jmliu88 
I am glad you found the project interesting. 
The right way to do it is to threshold angle of the intersection of curves after reading the SVG file, that is how https://github.com/Chlumsky/msdf-atlas-gen does it. 
I personally did it differently. I first converted the SVG files into MSDF format using https://github.com/Chlumsky/msdf-atlas-gen and then considered any pixel in MSDF format with more than 3 different colors in the neighborhood as a corner.

Regards,
Pradyumna.

**Comment by jmliu88** [comment]
Hi Pradyumna,

Thanks for your reply! It is very helpful.

By the way, I'm dealing with Chinese font generation task. Guess now I can implement it and see how it works in complex fonts like Chinese.

Regards,
James
